[Migration]
Hash = "13888833763972757380"
Initial = false
Dependency = 2
Replaces = []

[[Migration.Operations]]
Type = "CreateField"
Model = "attack"

[Migration.Operations.Field]
Name = "error"
Type = "varchar"

[[Migration.Operations.Field.Annotations]]
Type = "max_length"
Value = 255
