[Migration]
Hash = "6874385749746671027"
Initial = false
Dependency = 4
Replaces = []

[[Migration.Operations]]
Type = "CreateModel"
Name = "workspacetag"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[[Migration.Operations.Fields]]
Name = "name"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "unique"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations.Fields]]
Name = "color"
Type = "int32"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateModel"
Name = "hostglobaltag"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[[Migration.Operations]]
Type = "CreateModel"
Name = "hostworkspacetag"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[[Migration.Operations]]
Type = "CreateModel"
Name = "service"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[[Migration.Operations.Fields]]
Name = "name"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations.Fields]]
Name = "version"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields]]
Name = "comment"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateModel"
Name = "serviceglobaltag"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[[Migration.Operations]]
Type = "CreateModel"
Name = "serviceworkspacetag"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[[Migration.Operations]]
Type = "CreateModel"
Name = "port"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[[Migration.Operations.Fields]]
Name = "port"
Type = "int16"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations.Fields]]
Name = "protocol"
Type = "choices"

[[Migration.Operations.Fields.Annotations]]
Type = "choices"
Value = [
    "Unknown",
    "Tcp",
    "Udp",
]

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations.Fields]]
Name = "comment"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateModel"
Name = "portglobaltag"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[[Migration.Operations]]
Type = "CreateModel"
Name = "portworkspacetag"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[[Migration.Operations]]
Type = "CreateModel"
Name = "domain"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[[Migration.Operations.Fields]]
Name = "domain"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations.Fields]]
Name = "comment"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateModel"
Name = "domainglobaltag"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[[Migration.Operations]]
Type = "CreateModel"
Name = "domainworkspacetag"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[[Migration.Operations]]
Type = "CreateField"
Model = "service"

[Migration.Operations.Field]
Name = "host"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "host"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "service"

[Migration.Operations.Field]
Name = "port"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "port"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations]]
Type = "CreateField"
Model = "service"

[Migration.Operations.Field]
Name = "workspace"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "workspace"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "domainglobaltag"

[Migration.Operations.Field]
Name = "global_tag"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "globaltag"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "domainglobaltag"

[Migration.Operations.Field]
Name = "domain"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "domain"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "hostglobaltag"

[Migration.Operations.Field]
Name = "global_tag"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "globaltag"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "hostglobaltag"

[Migration.Operations.Field]
Name = "port"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "host"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "domainworkspacetag"

[Migration.Operations.Field]
Name = "workspace_tag"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "workspacetag"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "domainworkspacetag"

[Migration.Operations.Field]
Name = "domain"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "domain"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "portglobaltag"

[Migration.Operations.Field]
Name = "global_tag"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "globaltag"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "portglobaltag"

[Migration.Operations.Field]
Name = "port"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "port"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "serviceworkspacetag"

[Migration.Operations.Field]
Name = "workspace_tag"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "workspacetag"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "serviceworkspacetag"

[Migration.Operations.Field]
Name = "domain"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "service"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "hostworkspacetag"

[Migration.Operations.Field]
Name = "workspace_tag"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "workspacetag"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "hostworkspacetag"

[Migration.Operations.Field]
Name = "domain"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "host"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "serviceglobaltag"

[Migration.Operations.Field]
Name = "global_tag"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "globaltag"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "serviceglobaltag"

[Migration.Operations.Field]
Name = "port"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "service"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "port"

[Migration.Operations.Field]
Name = "host"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "host"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "port"

[Migration.Operations.Field]
Name = "workspace"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "workspace"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "portworkspacetag"

[Migration.Operations.Field]
Name = "workspace_tag"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "workspacetag"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "portworkspacetag"

[Migration.Operations.Field]
Name = "domain"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "port"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "domain"

[Migration.Operations.Field]
Name = "workspace"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "workspace"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "host"

[Migration.Operations.Field]
Name = "response_time"
Type = "int32"
Annotations = []
