[Migration]
Hash = "14505956474047081693"
Initial = false
Dependency = 15
Replaces = []

[[Migration.Operations]]
Type = "CreateModel"
Name = "manualhttpservice"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[[Migration.Operations.Fields]]
Name = "name"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations.Fields]]
Name = "domain"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields]]
Name = "ip_addr"
Type = "ipnetwork"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations.Fields]]
Name = "port"
Type = "int32"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations.Fields]]
Name = "port_protocol"
Type = "choices"

[[Migration.Operations.Fields.Annotations]]
Type = "choices"
Value = [
    "Unknown",
    "Tcp",
    "Udp",
    "Sctp",
]

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations.Fields]]
Name = "base_path"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 1024

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations.Fields]]
Name = "tls"
Type = "boolean"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations.Fields]]
Name = "sni_required"
Type = "boolean"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations.Fields]]
Name = "created_at"
Type = "datetime"

[[Migration.Operations.Fields.Annotations]]
Type = "auto_create_time"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateModel"
Name = "httpservice"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[[Migration.Operations.Fields]]
Name = "name"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations.Fields]]
Name = "base_path"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 1024

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations.Fields]]
Name = "tls"
Type = "boolean"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations.Fields]]
Name = "sni_required"
Type = "boolean"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations.Fields]]
Name = "comment"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 1024

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations.Fields]]
Name = "created_at"
Type = "datetime"

[[Migration.Operations.Fields.Annotations]]
Type = "auto_create_time"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateModel"
Name = "httpserviceglobaltag"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[[Migration.Operations]]
Type = "CreateModel"
Name = "httpserviceworkspacetag"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[[Migration.Operations]]
Type = "CreateField"
Model = "httpserviceglobaltag"

[Migration.Operations.Field]
Name = "global_tag"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "globaltag"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "httpserviceglobaltag"

[Migration.Operations.Field]
Name = "http_service"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "httpservice"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "manualhttpservice"

[Migration.Operations.Field]
Name = "user"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "user"
ColumnName = "uuid"
OnDelete = "Restrict"
OnUpdate = "Restrict"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "manualhttpservice"

[Migration.Operations.Field]
Name = "workspace"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "workspace"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "httpserviceworkspacetag"

[Migration.Operations.Field]
Name = "workspace_tag"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "workspacetag"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "httpserviceworkspacetag"

[Migration.Operations.Field]
Name = "http_service"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "httpservice"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "httpservice"

[Migration.Operations.Field]
Name = "domain"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "domain"
ColumnName = "uuid"
OnDelete = "SetNull"
OnUpdate = "Cascade"

[[Migration.Operations]]
Type = "CreateField"
Model = "httpservice"

[Migration.Operations.Field]
Name = "host"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "host"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "httpservice"

[Migration.Operations.Field]
Name = "port"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "port"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "httpservice"

[Migration.Operations.Field]
Name = "workspace"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "workspace"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "findingaffected"

[Migration.Operations.Field]
Name = "http_service"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "httpservice"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations]]
Type = "RawSQL"
StructureSafe = true
SQLite = "only Postgres databases are supported right now"
MySQL = "only Postgres databases are supported right now"
Postgres = "ALTER TYPE _aggregationsource_source_type ADD VALUE IF NOT EXISTS 'ManualHttpService' AFTER 'ManualService';"

[[Migration.Operations]]
Type = "RawSQL"
StructureSafe = true
SQLite = "only Postgres databases are supported right now"
MySQL = "only Postgres databases are supported right now"
Postgres = "ALTER TYPE _aggregationsource_aggregated_table ADD VALUE IF NOT EXISTS 'HttpService' AFTER 'Domain';"